extern long ssx, ssy, buf_x, buf_y;
extern long res_x, res_y, graph_drv, num_pages, active_page;
extern long gray_normal[], cmap[], cmap_dark[];
extern uchar *scr, *ubuf, *buf[], *icons[2][15];
extern uchar gray[], shade[], night_link[], *back[];
extern long win_size, num_pic[], rnds, rel_or_dir[2];
extern long debug, key_or_joy[2];
extern long sound_volume, music_volume, show_radar;
extern objectstruct *obj, *corrupted_object;
extern pictureinfotype *pic, *pictures[];
extern PALETTE pal, night_pal;
extern volatile long timer, game_pause;
extern internaltype intern[];
extern tankinfotype tank[];
extern maptype map;
extern mapmemtype mapm;
extern strengthtype strength;
extern gameinfo game;
extern effectstype eff[];
extern effectstruct *effect;
extern hitinfotype hit[];
extern keytype keys;
extern joytype joy;
extern BITMAP *scrbuf, *panel;
extern FONT *big_font;
extern int numprod[num_products];
extern int shareware;
